[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e65c3587485059b213468b4fe87148ef7fbc80bb"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "accd5b4236d651c32693ad9dc80862227fcf29c187535800effd70566e80c767"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.283+0/Reactant.v0.0.283.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6b2954a9bf01c42688183a7eefacb942c1ef56d"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "b8fcb6da66f4c7725af0e7569420fff1a6bf92776c2f339ba9a14f107c7f900a"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.283+0/Reactant.v0.0.283.aarch64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "c653a04a99d0bfd7489c1e54556de0dc4c20d17c"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "da467fecc4c8d571b70b4c55e1e030e21b0b7468a72540b1dfb1ced5f3abafc5"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.283+0/Reactant.v0.0.283.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "dbe5085a617ca6e890c87b9c378a93fb507eb4d1"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "c365f4fc15025d47560075ccdd40fa02f293cb337e746239b9a6ebb2796c9822"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.283+0/Reactant.v0.0.283.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72226cb69b92f60a74276b82910b66e6f837a63c"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "windows"

    [[Reactant.download]]
    sha256 = "4d6115d323902fcc2938b7189097966234439da84e8ea59c54f1279ed5b86e7a"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.283+0/Reactant.v0.0.283.x86_64-w64-mingw32-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "c3150b3a2b0cc7f68a8f13ba6030c930812c4eb1"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "94c8250c5106bae95e025dc2a17b462eaf33809fedc18a4d1cfc97ea332b4690"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.283+0/Reactant.v0.0.283.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "a22d954d4724dcd7abfc73c954406a0f97e9ecd3"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "c9b69eccfb494ff481448c947a3f90fda1cd3bb4ccf51ebd726beff6ac5f3695"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.283+0/Reactant.v0.0.283.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67c21c17ec6ff2928492fd6f6eb1ef40e86d5a43"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "7fbc44ade21d8b6f443bf3f9252e19c319333d8ce637ef3e6cca8632bee6cca6"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.283+0/Reactant.v0.0.283.x86_64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be7260e3e2b9824c86f8f6185765e52a3f2e02b0"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "44cc7639ab2750dfc40ce1ecb3f2c6de4e2e711e3845579467bcbb2a4e977c4a"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.283+0/Reactant.v0.0.283.aarch64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ab91a019143c6814bf7cda69d50a77e4023c2aa"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "aa6af76bdaf9146fe55e2bdca4bd9fb44fa0895cb25bd7e8d63dd96240afe9f4"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.283+0/Reactant.v0.0.283.x86_64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b5088210b95f3defa21bfbf7bc8a67e75777b0d"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "725fd1548c42a01e4829b13dfd89cac15cef1b94be24aa26c1a3dd289c187d62"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.283+0/Reactant.v0.0.283.aarch64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a41fb013cbb2926b6c2ced72a8b5701b9c3da65"
gpu = "rocm"
gpu_version = "7.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "2cbd98377fae9730f2c821a08e012244cbdbb7c51a08780b276b1bd1cd2d2e90"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.283+0/Reactant.v0.0.283.x86_64-linux-gnu-cxx11-gpu_version+7.1-gpu+rocm-mode+opt.tar.xz"
