[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e7deae1aa41e48e7ad9d5b1f52ed5bfe7af2928"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "4855a9b4be02491b69d06045649eb0e14aa4908e30e9965e02dcb05db70e6594"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcf1259c41d5393ce92e8388176fd2beff99980d"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "8fba8b8c7b38520eb2ce9e96171ed31c84c92d8543e95d7946960f9fea8ba57a"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.aarch64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "1b7e54de2998e60e2af019cab10aa3b74facf3e8"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "839928260c6450dfe8ade908a383821e6f095a8835e9d2821a167282271ed67b"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "dc6c52189bc8277634a65e2b7bf8d539139baf4b"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "78ce7919cdba28374d640192c51dcd1c11e3de22315523f084067f655cce95cd"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53f75bd129ef964fb13b91e0f121cbfcceb09796"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "windows"

    [[Reactant.download]]
    sha256 = "5406c576650109ee7bab4ab57365cb368aa902bcefb3b1bf082ace3720f3e02d"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.x86_64-w64-mingw32-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5c38ac2d77c4d6086da35c9514c5259f25e9e97"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "dbg"
os = "linux"

    [[Reactant.download]]
    sha256 = "2fa4708b54eedce25ce34507baa4c1ae3f377db2d10d2be63ea55f10c7881b69"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "d0aabb33fe1a9d0f0652005ac97ae89d36317483"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "33c9fa1caf4f081f8e0a7bf439d9683db51748aaf82f76b8f51061aeccc3f0fd"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "89dd4c7d0fdca577b84ca2da8e31b45c55db08ec"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "3947d4d497ef831c912eeebbc7cb9ab48edefbcfea66706bf51c714ce7368da9"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81a6dd827228dcd62fd6de55b02cc53688750402"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "760bca5807a26b6b79be66965fd26b7ce1cc0c582fa7bb89657d2fcb5c60a302"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.x86_64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5f8564f32311ebcaf25d7ba520c87086c705fc1"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "d4ca372f188173abaec16c40451a1165b6ed51ad231fd870f5f4e403bfa30740"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.aarch64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b786b30ac2a8bd2fbead76923a540eafe60a8438"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "a41006db3bcaafd8301cf3e7f711080787e86a6cf886184e19bf3f80adca004c"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.x86_64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb59bbbf79d14f2e305a80f40ddb06cdda36b312"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "359bc2e2bb01a287cfe04dcf757fe6ced25fbf39c66fb68fa21b369e05136288"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.aarch64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88f493d5baba7418a4287ce941e5e9cd5a3a52d0"
gpu = "rocm"
gpu_version = "7.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "292f5ed59cf2fdb63ae5b82c34c3fcffb771e0795ff3b40f9e7d0a3b28511056"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.304+0/Reactant.v0.0.304.x86_64-linux-gnu-cxx11-gpu_version+7.1-gpu+rocm-mode+opt.tar.xz"
