[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a30010b856f35bd77a057901625c6e92827a6cc4"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "eeabd92825dcb0af2c068217a46cfcb14ceb5f72138bc1a8b7629bc2f61884f5"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdb5ca7ea26882b15d0c19d034cd120a90b7f2c9"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "8557723a31c430c98e782261a9cd7972287d72624cbfe1ec7407dedf7f4c84d1"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.aarch64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "4dadaeb6428fbb64164afa729587413c2e745e34"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "3723b5e9e0715bfc21a2ce13529a502fdf0daa8120db27cd800ed7f24a262337"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "49e0e84b1d7f5bc633da157647bd8e00824a7ccc"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "71c8e54852cbcbb03eee69d35423c8729e46718bca204b11ab4a53a4954fb9f9"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "664fac3154a324a85d2e19a663eb6f8f9eb81bc2"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "windows"

    [[Reactant.download]]
    sha256 = "d800f0715c1a6c4507e5bcc7e97231c5a443e3249dab9f9ec8e6e6779e1f1a70"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.x86_64-w64-mingw32-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2c69a9cf938d2e45c7532dfb528cffa68b4c5c3"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "dbg"
os = "linux"

    [[Reactant.download]]
    sha256 = "9bcdde4f2ba21ddc88195c12ed756f93bf7db596b6933a12182194067c549e22"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "e34bd001775e5020eae9d4ecc5b93ee73d2fc2fa"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "701be6bf72f257e5fe0ff8251c42e1e23f3a4f3547fdb50e12607b909e787037"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "8609f86691d44ce33ce07013436a9a318c95dceb"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "b510c8f56e3360ee6e3fecfdd7df7f8f6e0f50461528e36f26f302638976ad2a"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "300f163a5c881b7e8ab418ba449e984f90e1f677"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "3623da4f93a6803b666fe98157f898424774ec5ca6077155c3f34ebc312002be"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.x86_64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ba0e8a9cdf848c5fb071f69c870f7eaf5273bc9"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "3266957ee47d88e3438dff90d17e5abb2d39a7e6d27346c637a9d8236b6674e3"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.aarch64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f1f4d0b87adb87c64fbdb6463d66e369d1afadc"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "ff51037030d71b3418ce0d6e3168b73ffca5dcfb9ac22822bc95111b9d19fc3d"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.x86_64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eaf31db6aea6b0428a4ea625f2518bdd2e80c02e"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "6054207d7b33ad2a5448c6d335a490c6e98288bf536e99d721efd8ed76f36544"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.aarch64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a2182e55ef4b865f582bd6df02a14842eca1a9c"
gpu = "rocm"
gpu_version = "7.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "8fb63266043fdd9448629a7f56d098bc194add1024223ca872bf8be6a42150e3"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.302+0/Reactant.v0.0.302.x86_64-linux-gnu-cxx11-gpu_version+7.1-gpu+rocm-mode+opt.tar.xz"
