[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a0a3352fb16aa8bbaad169507874b96b3e4956a"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "81cdf885bcc10ce588cd2bc84a3d0c5179306c0c48e561db0bdb9f73e0f90e0e"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.274+0/Reactant.v0.0.274.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdef60524bb3134fb7f9d7825c2a6b4ef675994c"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "e7d086a899e8bc74dcf0a0e51ff2961a860be64dbd6f7b39142a0df99dc0bab0"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.274+0/Reactant.v0.0.274.aarch64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "7182f327471c43c4c5a03afdb2704208173cc52c"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "650e1e5bb85c6e24bc285e32b1c19bd06d6652f43e9dae53918ab938f695dbd1"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.274+0/Reactant.v0.0.274.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "63a5e1f57e5d1c1789c0ee311c17b8adfcabda52"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "6467d1a864d7b188c950b9e230e9f9c9d36e0058853f01537deb8278ed1a3ed8"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.274+0/Reactant.v0.0.274.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "462bde3b2c03de3cb04782edd2cc4999cebabe10"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "windows"

    [[Reactant.download]]
    sha256 = "92bf2158219177c18d172b5be87bd1204ed2d0805f57b4dd9dcce72ed34e4478"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.274+0/Reactant.v0.0.274.x86_64-w64-mingw32-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "318f18f8f8fe17aec773dd661587bbc796aac1e0"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "6447c1f017918a895e3278e41f1c36d432ce1607bdc27cf5f2a53e6553098955"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.274+0/Reactant.v0.0.274.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "2e65e31ddc04f8a2e672de50c4f1227877f47ffc"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "d4b1e74ee36b249e85966969cd0fb66908a6e25509b8b068112a8d5580bc1e14"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.274+0/Reactant.v0.0.274.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb66d00f7c56637c720d0a1472b401f3e4690cf4"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "636d6b8dd46feba0a63a39d6291691e2cb19a7579a45816ec2ec7338219d624b"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.274+0/Reactant.v0.0.274.x86_64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d347806b7326ef8bcbd626f9e3a9578134a1682"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "5c5497e8937d277f87c0749a32d2dd6a6065706a388f90a53c01961e4e1c3f65"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.274+0/Reactant.v0.0.274.aarch64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71813415e55e763428db4112c4e8e8b6710e9cfd"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "885b92ecc83f0361b6b20b5f198d75ee12e93884eafb96ee09bfa2344b2b00b8"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.274+0/Reactant.v0.0.274.x86_64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3557a2d2f87c16e1400d9ec0cce88d854484876e"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "da0ad0b1f4aa99a7bdb5c9482679bafc9f03ccfa7fb78ee268daf0b8ed5813e2"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.274+0/Reactant.v0.0.274.aarch64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad9644ec340360ac7b9b09b186307689bacae2d3"
gpu = "rocm"
gpu_version = "7.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "e0ce3f219b0506d214e1eb0bc02a4457e702643f9a56958e7588c367de301ea4"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.274+0/Reactant.v0.0.274.x86_64-linux-gnu-cxx11-gpu_version+7.1-gpu+rocm-mode+opt.tar.xz"
