[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1362178911e97c8a5b13b82c98c6a773e1c472d"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "533198b693b2cbbdf0af1e83bceeaf7f865cb21b2e364d3a5f0c8c62bd6bfede"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.260+0/Reactant.v0.0.260.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "222dd4f53aaaf515afe4faf3526ade182f3d4299"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "1728994abad330869b35239124f117465c3f84a4b056120837053713677bc5a1"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.260+0/Reactant.v0.0.260.aarch64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "bffc3159aae4bb98f556ee4735e651f9d3cf3367"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "e8c71bf8c5ea7e3acc62c001a07922c7eb4ab659525760b1aa74b04afe8fce80"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.260+0/Reactant.v0.0.260.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "9d62da91988f467b319da4bc292f36d4e6dcd8db"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "aa427db1ea4c1959431ffd3c72fbcbb094e3482387fd7d51fa679f0b7091ba5f"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.260+0/Reactant.v0.0.260.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78a25598b3cc8b41578fb107b95affb1a26b98db"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "windows"

    [[Reactant.download]]
    sha256 = "fceb9d545fdd819cc726fde480d15976439d43db8b48ee9228b75b69cc679957"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.260+0/Reactant.v0.0.260.x86_64-w64-mingw32-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "88bcdcd9ea065ba549708898ea1c703ed6e80eda"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "9b22a4eb8d0bdb44b7a9751f89460a7dfbb95d6303d932fde0ea3458e3425267"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.260+0/Reactant.v0.0.260.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "191c29338e096fcc3273359305549a2203fbeab8"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "4ebdd07583f1e32439cc99c6e589535840644232087216e59de3e552aab50faf"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.260+0/Reactant.v0.0.260.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1073748e79de6db96431a65d1ba34688d8c049e"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "ba1acd64150ed33c4fc55ed0756b6f4a476e4096a613c09d64537349edf67152"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.260+0/Reactant.v0.0.260.x86_64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc0d71e1a088ecd7f49b196c828bbb1fd50d9c8f"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "2237ec1b1fff406484b79c62170224e822c80a6f360a3b13cc20bf56876f57f4"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.260+0/Reactant.v0.0.260.aarch64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c7bef9ebe785d0c518605ded8637c49d224ed86"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "3b2485ff720e7a765b3bbdab65fa02269f4caea0b554d316f17359b4a453b57c"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.260+0/Reactant.v0.0.260.x86_64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44566ae45abb3a759bd19d62f113d5e96a732f58"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "0196c6b324ef9e51e4a561eec99aeb54980f205121224ee13e752dfe29a9b436"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.260+0/Reactant.v0.0.260.aarch64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24f44da2cbc8239649617e0e327389cad7c64911"
gpu = "rocm"
gpu_version = "7.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "1c347dc11fa7b730e89f59201479b12576e7a28374056f193c875891c9035caf"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.260+0/Reactant.v0.0.260.x86_64-linux-gnu-cxx11-gpu_version+7.1-gpu+rocm-mode+opt.tar.xz"
