[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79349b1fe0d9b919f1e60a92fb85b9691e124db1"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "2ce9b7d7c8b0bf55446588248f50174df4981f428b33cd493ab2f7975c68d6c5"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30a367168414176489d259281b142233f5ff3cb0"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "7aa20dd03d69c2651676ae5b809b866e9590cd67e453ac5fcf528836a9309b29"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.aarch64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "4b4f842eb5f7bfe05c178c214e7cc851c4950802"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "cbf4946f8575a6f4ff9723afb8c62d76ff68e8295b9b65c70814d33b79238e7e"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "240f64079325c953e8d3f560386d9aec6dc77eeb"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "accac399ca7f3d31a25f06ba65a10a7ce470022adfcdb2cc4d55ae9131b253e1"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "582338d86f54c61df4d8c1435a39ab571c7a9253"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "windows"

    [[Reactant.download]]
    sha256 = "491e7d9043407245c60fd12a7202ac65c0ac0f2e4a0ff8e526151787f444f9ce"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.x86_64-w64-mingw32-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a89b5fa5c095b4ae0dc7388cc906bcd855d47ad8"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "dbg"
os = "linux"

    [[Reactant.download]]
    sha256 = "09c3fce76e79c31733aa1d67908799c1c9c006a604425b5eb812e4b6b2d1fdf2"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "b8ed6a9d353e84884f989cb6737409d96d6d420c"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "597e8b50fabd4901907bed11452d4493b638aa2c673906879519badb01fbb0e9"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "694d8139081abf953500f04d1d47296c6d49b008"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "95a92861fc8eac8ec63cc06b33cff811750c0e48e521cc93d7a6dcd821ca5e82"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf44851bc33d1b482dd21468e328bd7e50689baf"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "1dd7b35f46315b0ce02eb721afad34aa379703fa9cb93eeb47dc3a58bea0e8b1"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.x86_64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "173895c745fd5381c1b0c1af055380c51a9b7a2f"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "7fc94d537309315df463a128553bdc42aebdb5defad4cd5381adbcfd2c88b0ac"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.aarch64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06e125ac46d879ad02a66d71a542feafef0fba7b"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "460fb976d20d5a9a57859be16f12f7e26987ffdfc9bdec4311ef6d7a58f10372"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.x86_64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcf119effff264ff359a6dcadbc9e176670077f9"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "96b4372bf2757bde8f08727fc7dfb25361c3df6ac09b03b0fda1e8a07f77fe8b"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.aarch64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea6f91ba15b4cf5ce3c9d67546e703bf91e28aaf"
gpu = "rocm"
gpu_version = "7.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "ffcc0a530bf6139f1446312cb0400cf7f92474c4aea23b7c0a19d80829335abf"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.332+0/Reactant.v0.0.332.x86_64-linux-gnu-cxx11-gpu_version+7.1-gpu+rocm-mode+opt.tar.xz"
