[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af9023448b4f0776b6c7d95fe645968ee5236640"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "cd2e0efba83490b2e4267f7a206bd652ca6d03dd890e92e85c5a192b637f262d"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a10cfded0e9a33d6698729da3fa7ade315cee93f"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "01ca144c7c63a5513939a5bc4c12dc38fbb86d8dd4c70d2e8e4987d8f74e8f59"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.aarch64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "7c22914b194f34fee5a199ada69f54982fc7fba7"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "7d5b5d0ed316a1cfb1d3dcdbc1f3fe505d329ebd01d5544deeadc1dc157563f8"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "63c349e65aa512e9fe5f439f378a30f36a8f6abc"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "67e174fcc52764f9f28f18fc0603c9e1d7c697e1d438da00d92f2daa6d67332a"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "412dfc72709bb220efb8e9b8637149ecf381cab5"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "windows"

    [[Reactant.download]]
    sha256 = "3b148b5a81850804d7147295ec568517f055e5c6b30542e92a776c6157b72ad9"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.x86_64-w64-mingw32-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8c80a56f583ffa1dab6c7fa6487aeb30e1db74e"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "dbg"
os = "linux"

    [[Reactant.download]]
    sha256 = "3ff1f50366ccb141c4f48833538aa3ff3ad87438f64b71e6bda934de3d9231a5"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "db7ce3198636ceafae6c097f1303e129f9842898"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "c986108dcb0f393d8e7192c74e5459c4a0283f034f3692314a1f767b9998b5fd"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "b3baa7a3d2dc9b45a4754e44e86168cd379c43e6"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "b23c18bc08067f98c0ea5cd8aa170a2950089fb98a7effe542ddb9c978de5c09"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "beca913f90f3e0450ec91c7bd395c865696afc3a"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "ec15b8c11beb845d6374714006f6d3f0e77873d253fc1afd320e55325e7e3f58"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.x86_64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b43214915b7996d6efbfb79fc563d374bdd39821"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "82c6a36f4061bead2e08681bd67388f545b1a0175489bf5a2152b37d7f12e9d6"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.aarch64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "517fed2eb23181e97d7504e719518c4bfb90b394"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "1c98c012e7110fe56a45a7844f79ab3a3fca31b28b63510cc12af3b7cabd53af"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.x86_64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f3109adcc23904e0f42b6cbdb210e9c32b8e664"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "be0e96a6595c17d2188585f96eb6d88820d49061a693329588056d553ca14743"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.aarch64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "449ef14a289cd3ea31c22a827493004edc50f61e"
gpu = "rocm"
gpu_version = "7.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "c8acc2f501d9fc10a4ad09069b3682a00ce31298f74bde1eb1bef89ba89b7fec"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.323+0/Reactant.v0.0.323.x86_64-linux-gnu-cxx11-gpu_version+7.1-gpu+rocm-mode+opt.tar.xz"
